### ISSUE TITLE
INTERACTION_ALREADY_REPLIED

### ISSUE THREAD

**Issue by Shirishx01** [WillTDA/Discord.js-Akinator-Package-Dev#15]
I have enabled butttons so when i click a button the bot doesn't responds and there's an error in the console log saying
Error [INTERACTION_ALREADY_REPLIED]: The reply to this interaction has already been sent or deferred.

**Comment by WillTDA** [comment]
Hello 👋 Odd behaviour, this hasn't happened to anyone else before. Can you show me your code and tell me if you're using a CommandInteraction, or Message as input?

**Comment by WillTDA** [comment]
Since you haven't replied in over a day, I'll assume you fixed the issue 👍
