### ISSUE TITLE
ahhh dosent work in slash

### ISSUE THREAD

**Issue by Atharvat007** [WillTDA/Discord.js-Akinator-Package-Dev#16]
it is not working in slash

**Comment by WillTDA** [comment]
Can you tell me the things below so I can help you?

- Your code
- Discord.js Version
- D.js Akinator Version
- Node Version (`node -v` in terminal)

**Comment by WillTDA** [comment]
Since there has been no reply in 3 days, I'll assume the problem has been fixed 👍
