### ISSUE TITLE
Bad french translations

### ISSUE THREAD

**Issue by Telepathique** [WillTDA/Discord.js-Akinator-Package-Dev#29]
hello somes of the french translation are verry bad and make no sense maybe try to find a french to translate them correctly because google made it wrong :)

```json
{
    "gameEnded": "Jeu terminé",
    "gameEndedDesc": "Votre jeu est terminé car : 1 minute d'inactivité.",
    "question": "Question",
    "progress": "Progrès",
    "pleaseType": "Veuillez saisir ...",
    "stopTip": "Vous pouvez également taper \"s\" ou \"arrêter\" pour mettre fin à votre jeu.",
    "yes": "Oui",
    "no": "Non",
    "dontKnow": "Je ne sais pas",
    "dontKnowNoComma": "Ne sais pas",
    "probably": "peut-être",
    "probablyNot": "peut-être pas",
    "back": "Retour",
    "stop": "Arrêter",
    "thinking": "Réfléchis...",
    "isThisYourCharacter": "Est-ce votre personnage?",
    "ranking": "Classement",
    "noOfQuestions": "Nombre de questions",
    "wellPlayed": "Bien joué!",
    "guessedRightOneMoreTime": "J'ai deviné encore une fois de plus!",
    "character": "Personnage",
    "defeated": "Bravo! Tu m'as vaincu ...",
    "gameForceEnd": "Votre jeu est terminé avec succès!"
}
```

i fixed this one to be more "human like" but the main questions where are they ?

**Comment by Telepathique** [comment]
![image](https://user-images.githubusercontent.com/30240088/160225132-07da0686-7517-448e-bc4d-da22c9c422df.png)
 should be : Est-ce que votre personnage est de sexe féminin  not as shown in picture my eyes are bleeding to see this :(

**Comment by WillTDA** [comment]
Hello! 👋

Sorry for the inaccurate translations. I'll have them fixed in the next release, so I'll keep this issue open until then.

As for the questions, they are translated in real-time so hard-coding translations for those would not only be very difficult, but would also heavily impact the package size 😕

**Comment by Telepathique** [comment]
> Hello! 👋
> 
> Sorry for the inaccurate translations. I'll have them fixed in the next release, so I'll keep this issue open until then.
> 
> As for the questions, they are translated in real-time so hard-coding translations for those would not only be very difficult, but would also heavily impact the package size 😕

its okay i can understand :)
