### ISSUE TITLE
Bad turkish translations 

### ISSUE THREAD

**Issue by thetomentosa** [WillTDA/Discord.js-Akinator-Package-Dev#31]
{
    "gameEnded": "Oyun sona erdi",
    "gameEndedDesc": "Oyununuz 1 dakikalık hareketsizlik nedeniyle sona erdi.",
    "question": "Soru",
    "progress": "İlerleme",
    "pleaseType": "Lütfen yazın...",
    "stopTip": "Oyununuzu sonlandırmak için \"S\" veya \"durdur\" yazabilirsiniz.",
    "yes": "Evet",
    "no": "Hayır,
    "dontKnow": "Bilmiyorum",
    "dontKnowNoComma": "Bilmiyorum",
    "probably": "Muhtemelen",
    "probablyNot": "Muhtemelen değil",
    "back": "Geri",
    "stop": "Dur",
    "thinking": "Düşünme ...",
    "isThisYourCharacter": "Bu senin karakterin mi?",
    "ranking": "Sıralama",
    "noOfQuestions": "Soru Sayısı",
    "wellPlayed": "Güzel oynadı!",
    "guessedRightOneMoreTime": "Doğru bir kez daha tahmin ettim!",
    "character": "Karakter",
    "defeated": "Bravo! Beni yendin ...",
    "gameForceEnd": "Oyunun başarıyla sona erdi!"
}

**Comment by WillTDA** [comment]
Thank you for providing the corrections. I'll implement them accordingly in the next patch 😃
